#!/usr/bin/env python3
"""
Generate pre-rendered colored digit bitmaps for throttle mode.

Reads the existing white digit images from ui_images.c, applies Tixing-style
color tinting with proper anti-aliasing preservation, and outputs a C source
file with 11 color variants (0%-100% in 10% steps).

Color gradient (matches Tixing exactly):
  0%  = Blue    (0, 180, 255)
  50% = Yellow  (255, 210, 80)
  100% = Red    (255, 40, 30)
"""

import re
import os

# Tixing color stops
LO = (0, 180, 255)    # Blue
MID = (255, 210, 80)  # Yellow
HI = (255, 40, 30)    # Red

def lerp_color(c1, c2, t):
    t = max(0.0, min(1.0, t))
    return (
        int(c1[0] + (c2[0] - c1[0]) * t),
        int(c1[1] + (c2[1] - c1[1]) * t),
        int(c1[2] + (c2[2] - c1[2]) * t),
    )

def speed_color(percent):
    t = percent / 100.0
    if t <= 0.5:
        return lerp_color(LO, MID, t * 2.0)
    else:
        return lerp_color(MID, HI, (t - 0.5) * 2.0)

def rgb565_to_rgb888(hi, lo):
    val = (hi << 8) | lo
    r = ((val >> 11) & 0x1F) * 255 // 31
    g = ((val >> 5) & 0x3F) * 255 // 63
    b = (val & 0x1F) * 255 // 31
    return r, g, b

def rgb888_to_rgb565_be(r, g, b):
    val = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return (val >> 8) & 0xFF, val & 0xFF

def tint_pixel(src_r, src_g, src_b, tint_r, tint_g, tint_b):
    # Perceptual luminance
    lum = (src_r * 299 + src_g * 587 + src_b * 114) / 1000.0 / 255.0
    # Gamma curve for natural look
    lum = lum ** 0.85
    out_r = min(255, int(tint_r * lum))
    out_g = min(255, int(tint_g * lum))
    out_b = min(255, int(tint_b * lum))
    return out_r, out_g, out_b

def parse_image_data(c_source, name):
    start_pattern = rf'const unsigned char {re.escape(name)}\[\d+\]\s*=\s*\{{'
    match = re.search(start_pattern, c_source)
    if not match:
        return None
    start_idx = match.end()
    brace_count = 1
    idx = start_idx
    while idx < len(c_source) and brace_count > 0:
        if c_source[idx] == '{': brace_count += 1
        elif c_source[idx] == '}': brace_count -= 1
        idx += 1
    content = c_source[start_idx:idx-1]
    hex_values = re.findall(r'0[xX][0-9A-Fa-f]+', content)
    return bytes([int(v, 16) for v in hex_values])

def generate_colored_digit(raw_data, tint_rgb):
    result = bytearray()
    tint_r, tint_g, tint_b = tint_rgb
    for i in range(0, len(raw_data), 2):
        src_r, src_g, src_b = rgb565_to_rgb888(raw_data[i], raw_data[i+1])
        if src_r == 0 and src_g == 0 and src_b == 0:
            result.extend(b'\x00\x00')
        else:
            out_r, out_g, out_b = tint_pixel(src_r, src_g, src_b, tint_r, tint_g, tint_b)
            hi, lo = rgb888_to_rgb565_be(out_r, out_g, out_b)
            result.append(hi)
            result.append(lo)
    return bytes(result)

def main():
    src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'main', 'resources', 'ui_images.c'))
    print(f"Reading: {src_path}")
    with open(src_path, 'r', encoding='utf-8', errors='ignore') as f:
        c_source = f.read()

    digit_names = [
        "gImage_speed_0_5153",
        "gImage_speed_1_1553",
        "gImage_speed_2_4853",
        "gImage_speed_3_4353",
        "gImage_speed_4_5153",
        "gImage_speed_5_4653",
        "gImage_speed_6_4953",
        "gImage_speed_7_4653",
        "gImage_speed_8_4953",
        "gImage_speed_9_4953",
    ]
    HEIGHT = 53

    print("Parsing digit bitmaps...")
    digit_data = []
    for name in digit_names:
        data = parse_image_data(c_source, name)
        if data is None:
            print(f"  ERROR: {name} not found")
            return
        width = len(data) // 2 // HEIGHT
        print(f"  {name}: {len(data)} bytes, {width}x{HEIGHT}")
        digit_data.append((name, data, width))

    color_steps = 11
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'main', 'resources', 'colored_digits.c'))
    hdr_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'main', 'resources', 'colored_digits.h'))

    print(f"\nGenerating {color_steps} color variants...")
    total_bytes = 0

    with open(out_path, 'w') as f:
        f.write("/* Auto-generated colored digit bitmaps for throttle mode */\n")
        f.write("/* Generated by tools/gen_colored_digits.py */\n")
        f.write('#include "colored_digits.h"\n\n')

        for ci in range(color_steps):
            percent = ci * 10
            color = speed_color(percent)
            print(f"  Step {ci} ({percent}%): RGB({color[0]},{color[1]},{color[2]})")

            for digit_idx, (name, data, width) in enumerate(digit_data):
                colored = generate_colored_digit(data, color)
                arr_name = f"gImage_speed_{digit_idx}_c{ci}"
                f.write(f"const unsigned char {arr_name}[{len(colored)}] = {{\n")
                for row in range(0, len(colored), 16):
                    chunk = colored[row:row+16]
                    f.write("  " + ",".join(f"0x{b:02X}" for b in chunk) + ",\n")
                f.write("};\n\n")
                total_bytes += len(colored)

    with open(hdr_path, 'w') as f:
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define COLORED_DIGIT_STEPS {color_steps}\n\n")
        for ci in range(color_steps):
            for digit_idx, (name, data, width) in enumerate(digit_data):
                f.write(f"extern const unsigned char gImage_speed_{digit_idx}_c{ci}[{len(data)}];\n")
            f.write("\n")

    print(f"\nDone! Total: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")
    print(f"Output: {out_path}")
    print(f"Header: {hdr_path}")

if __name__ == '__main__':
    main()
