"""
Convert WAV files to C header arrays for the engine sound synthesizer.
Usage: python wav_to_header.py <idle.wav> <rev.wav>
Output: engine_idle.h, engine_rev.h in main/resources/
"""
import struct, sys, os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RES_DIR = os.path.join(SCRIPT_DIR, '..', 'main', 'resources')

def wav_to_int8_array(wav_path):
    """Read WAV (including 32-bit float), convert to mono 8-bit signed PCM."""
    with open(wav_path, 'rb') as f:
        data = f.read()
    
    # Parse RIFF header manually to handle extended WAV formats
    assert data[:4] == b'RIFF', "Not a RIFF file"
    assert data[8:12] == b'WAVE', "Not a WAVE file"
    
    # Find fmt and data chunks
    pos = 12
    fmt_data = None
    audio_data = None
    while pos < len(data) - 8:
        chunk_id = data[pos:pos+4]
        chunk_size = struct.unpack('<I', data[pos+4:pos+8])[0]
        if chunk_id == b'fmt ':
            fmt_data = data[pos+8:pos+8+chunk_size]
        elif chunk_id == b'data':
            audio_data = data[pos+8:pos+8+chunk_size]
        pos += 8 + chunk_size
        if pos % 2 == 1:  # chunks are word-aligned
            pos += 1
    
    assert fmt_data and audio_data, "Missing fmt or data chunk"
    
    audio_format = struct.unpack('<H', fmt_data[0:2])[0]
    nch = struct.unpack('<H', fmt_data[2:4])[0]
    sr = struct.unpack('<I', fmt_data[4:8])[0]
    bits = struct.unpack('<H', fmt_data[14:16])[0]
    
    # Format 3 = IEEE float, Format 0xFFFE = extensible (check subformat)
    is_float = (audio_format == 3)
    if audio_format == 0xFFFE and len(fmt_data) >= 40:
        subformat = fmt_data[24:40]
        # IEEE float GUID: 00000003-0000-0010-8000-00aa00389b71
        if subformat[:2] == b'\x03\x00':
            is_float = True
    
    print(f"  Input: {nch}ch, {bits}-bit, {'float' if is_float else 'int'}, {sr}Hz, {len(audio_data)} bytes")
    
    # Decode to float samples (mono)
    samples = []
    bytes_per_sample = bits // 8
    frame_size = bytes_per_sample * nch
    
    for i in range(0, len(audio_data) - frame_size + 1, frame_size):
        if is_float and bits == 32:
            val = struct.unpack_from('<f', audio_data, i)[0]
        elif is_float and bits == 64:
            val = struct.unpack_from('<d', audio_data, i)[0]
        elif bits == 16:
            val = struct.unpack_from('<h', audio_data, i)[0] / 32768.0
        elif bits == 8:
            val = (audio_data[i] - 128) / 128.0
        elif bits == 24:
            b = audio_data[i:i+3]
            val = struct.unpack('<i', b + (b'\xff' if b[2] & 0x80 else b'\x00'))[0] / 8388608.0
        elif bits == 32 and not is_float:
            val = struct.unpack_from('<i', audio_data, i)[0] / 2147483648.0
        else:
            val = 0.0
        samples.append(val)
    
    # Normalize to use full range
    peak = max(abs(s) for s in samples) if samples else 1.0
    if peak > 0:
        samples = [s / peak for s in samples]
    
    # Convert to int8 (-127..127)
    int8_samples = []
    for s in samples:
        val = int(s * 127)
        val = max(-127, min(127, val))
        int8_samples.append(val)
    
    print(f"  Output: {len(int8_samples)} samples, range [{min(int8_samples)}, {max(int8_samples)}]")
    return int8_samples, sr

def write_header(filename, var_prefix, samples, sample_rate):
    """Write C header file with sample array."""
    path = os.path.join(RES_DIR, filename)
    
    with open(path, 'w') as f:
        f.write(f'/**\n')
        f.write(f' * @file {filename}\n')
        f.write(f' * @brief Engine sound sample - generated by wav_to_header.py\n')
        f.write(f' * Format: {sample_rate} Hz, 8-bit signed PCM, mono\n')
        f.write(f' */\n')
        f.write(f'#pragma once\n')
        f.write(f'#include <stdint.h>\n\n')
        f.write(f'#define ENGINE_{var_prefix}_SAMPLE_RATE   {sample_rate}\n')
        f.write(f'#define ENGINE_{var_prefix}_SAMPLE_COUNT  {len(samples)}\n\n')
        f.write(f'static const int8_t engine_{var_prefix.lower()}_samples[] = {{\n')
        
        # Write 16 values per line
        for i in range(0, len(samples), 16):
            chunk = samples[i:i+16]
            line = ', '.join(f'{v}' for v in chunk)
            if i + 16 < len(samples):
                f.write(f'{line},\n')
            else:
                f.write(f'{line},\n')
        
        f.write(f'}};\n')
    
    size_kb = len(samples) / 1024
    print(f"  -> {filename}: {len(samples)} samples ({size_kb:.1f} KB)")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python wav_to_header.py <idle.wav> <rev.wav>")
        sys.exit(1)
    
    idle_wav = sys.argv[1]
    rev_wav = sys.argv[2]
    
    print(f"Converting idle: {idle_wav}")
    idle_samples, idle_sr = wav_to_int8_array(idle_wav)
    
    print(f"\nConverting rev: {rev_wav}")
    rev_samples, rev_sr = wav_to_int8_array(rev_wav)
    
    print(f"\nWriting headers...")
    write_header('engine_idle.h', 'IDLE', idle_samples, idle_sr)
    write_header('engine_rev.h', 'REV', rev_samples, rev_sr)
    
    print(f"\nDone! Headers written to {RES_DIR}")
    print(f"Total Flash: {(len(idle_samples) + len(rev_samples)) / 1024:.1f} KB")
